<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm_repeatedPassword</name>
   <tag></tag>
   <elementGuidId>aafbb88d-40de-495b-8abb-388acf15b7df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#repeatedPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='repeatedPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#repeatedPassword</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2386fc6-e076-4549-ae82-57b39c9026d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repeatedPassword</value>
      <webElementGuid>bb0893db-ad4d-4f44-879d-63effbb35a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeatedPassword</value>
      <webElementGuid>3cb6a0b4-e7ff-498f-b30d-2941fd0428c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c719c722-9647-4f54-b8fc-a70d7c9482a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d8540818-6d9e-4ed0-b138-f0b5ff186d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeatedPassword&quot;)</value>
      <webElementGuid>2a87c226-5da9-4cd8-8167-c1dd4e7c41c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='repeatedPassword']</value>
      <webElementGuid>b60b5d50-77b3-452b-ab42-6d2c030ebe2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customerForm']/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>3365f128-b80a-486e-ab9e-ebe085542170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[2]/input</value>
      <webElementGuid>60c8c33f-ff47-4fb5-9241-3a9f3bec1ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'repeatedPassword' and @name = 'repeatedPassword' and @type = 'password']</value>
      <webElementGuid>72aacf6a-b89f-4e2a-a86a-551f1ff3508c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
