<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Down Payment_downPayment</name>
   <tag></tag>
   <elementGuidId>79e39b37-0a69-416f-b809-e914d878a5bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#downPayment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='downPayment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#downPayment</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dc89470-a23b-464a-8004-3df43c5b281c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downPayment</value>
      <webElementGuid>05a3c990-c360-462c-90ab-52d6533aa962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-untouched ng-valid ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>1400f4ac-cbe4-4381-84b1-b4d26539badb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>loanRequest.downPayment</value>
      <webElementGuid>803a5d99-e853-49d1-9c25-3ce221d0fd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downPayment&quot;)</value>
      <webElementGuid>6fb0c5a0-e305-442b-ac1c-fbd45285407b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='downPayment']</value>
      <webElementGuid>13f90281-1095-40cb-99d9-bf0f3f386989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>0be1557e-f9f9-4ce0-8ded-89c7a6f1aaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>3ecce60c-71db-4785-859a-94db674aabc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'downPayment']</value>
      <webElementGuid>3a9e141b-e5bd-4146-bc91-32fef0011bdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
