<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_payee.phoneNumber</name>
   <tag></tag>
   <elementGuidId>0d87e6f0-93ef-4fd5-b580-0133b7f90e57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3a90f727-3e9e-4c86-91a8-d3ee021cb592</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='3a90f727-3e9e-4c86-91a8-d3ee021cb592']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;payee\.phoneNumber&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9576f74-c5d1-4cd5-a327-39e52ecb5f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3a90f727-3e9e-4c86-91a8-d3ee021cb592</value>
      <webElementGuid>15d4b388-345a-4c45-86ae-92fff56120fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input phone-number-3a90f727-3e9e-4c86-91a8-d3ee021cb592 ng-untouched ng-valid ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>872e2da3-9590-45a6-8eff-ac2f5285ea3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>payee.phoneNumber</value>
      <webElementGuid>5e920729-c122-4785-a544-2c44baa56386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee.phoneNumber</value>
      <webElementGuid>8c668a6d-b4c5-4362-9e73-b67054ef481e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3a90f727-3e9e-4c86-91a8-d3ee021cb592&quot;)</value>
      <webElementGuid>23ed6234-51ad-401b-9a6f-78cff82d2f19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='3a90f727-3e9e-4c86-91a8-d3ee021cb592']</value>
      <webElementGuid>37320247-926e-43c9-8607-91c1fde491dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>8b6e07bf-06fe-4d21-9182-708db3bae02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>544c6295-9207-42a1-956c-03abf9ca2063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '3a90f727-3e9e-4c86-91a8-d3ee021cb592' and @name = 'payee.phoneNumber']</value>
      <webElementGuid>ef712c1e-13ed-4c43-9733-0805ce340809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
